from fpdf import FPDF
import io
import re


def clean_text(text: str) -> str:
    """Remove markdown symbols and clean text for PDF"""
    # Remove bold/italic markers
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    # Remove markdown headers
    text = re.sub(r'#{1,6}\s+', '', text)
    # Remove emoji (basic cleanup)
    text = text.encode('ascii', 'ignore').decode('ascii')
    # Clean up extra spaces
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def generate_pdf(title: str, content: str) -> bytes:
    """
    Generate a professional PDF from text content
    Returns PDF as bytes for download
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────
    pdf.set_fill_color(102, 126, 234)  # Purple brand color
    pdf.rect(0, 0, 210, 35, 'F')

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 10)
    pdf.cell(190, 10, title, align="C")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(10, 22)
    pdf.cell(190, 8, "Remote Job Finder AI", align="C")

    # ── Divider ─────────────────────────────────────────
    pdf.set_draw_color(102, 126, 234)
    pdf.set_line_width(0.5)
    pdf.line(10, 38, 200, 38)

    # ── Content ─────────────────────────────────────────
    pdf.set_text_color(40, 40, 40)
    pdf.set_xy(10, 45)

    clean_content = clean_text(content)
    lines = clean_content.split('\n')

    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue

        # Section headers (ALL CAPS or ends with colon)
        if line.isupper() or (line.endswith(':') and len(line) < 50):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(102, 126, 234)
            pdf.set_x(10)
            pdf.multi_cell(190, 7, line)
            pdf.set_text_color(40, 40, 40)

        # Bullet points
        elif line.startswith(('-', '*', '•')):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_x(15)
            pdf.multi_cell(185, 6, "• " + line.lstrip('-*• ').strip())

        # Normal text
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_x(10)
            pdf.multi_cell(190, 6, line)

        pdf.ln(1)

    # ── Footer ──────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by Remote Job Finder AI", align="C")

    # Return as bytes
    return bytes(pdf.output())
